In [1]:
import torch
torch.__version__

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from torch.autograd import Variable

## Tensor 소개

##### 스칼라(0차원 텐서)

In [55]:
x = torch.tensor(10)
print(x)
print(x.size())
print(x.dim())

tensor(10)
torch.Size([])
0


##### 스칼라(1차원 텐서)

In [54]:
y = torch.rand(10)
print(y)
print(y.size())
print(y.dim())

tensor([0.5797, 0.6132, 0.9907, 0.4722, 0.3113, 0.1501, 0.4470, 0.8560, 0.9014,
        0.9510])
torch.Size([10])
1


##### 벡터(1차원 텐서)

In [56]:
temp = torch.FloatTensor([23, 24, 24.5, 26, 27.2, 23.0])
print(temp)
print(temp.size())
print(temp.dim())

tensor([23.0000, 24.0000, 24.5000, 26.0000, 27.2000, 23.0000])
torch.Size([6])
1


##### 행렬(2차원 텐서)

In [34]:
from sklearn.datasets import load_boston

boston = load_boston()
print(boston.data.shape)

(506, 13)


In [20]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [39]:
boston_tensor = torch.from_numpy(boston.data)
boston_tensor.size()

torch.Size([506, 13])

In [26]:
boston_tensor[:2]

tensor([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01, 6.5750e+00,
         6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02, 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01, 6.4210e+00,
         7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02, 1.7800e+01, 3.9690e+02,
         9.1400e+00]], dtype=torch.float64)

→ 첫번째 차원에서, 0번 인덱스 값부터 1번 인덱스 값을 출력
(1행부터 2행까지 출력)

In [29]:
boston_tensor[:10, :5]

tensor([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01],
        [3.2370e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01],
        [6.9050e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01],
        [2.9850e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01],
        [8.8290e-02, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01],
        [1.4455e-01, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01],
        [2.1124e-01, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01],
        [1.7004e-01, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01]],
       dtype=torch.float64)